blank_issues_enabled: false
contact_links:
  - name: GitHub Community Support
    url: https://github.com/community/community/discussions/categories/general
    about: Please ask and answer questions here.
  - name: Security Vulnerability
    url: https://github.com/your-username/your-repo/security/advisories/new
    about: Please report security vulnerabilities privately.
